import { Header } from '@/component';
import './globals.css';
import { Montserrat } from 'next/font/google';
import Providers from './providers';

const monserrat = Montserrat({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={monserrat.className}>
				<Providers children={children}>
					<Header />
					{children}
					<p>Footer</p>
				</Providers>
			</body>
		</html>
	);
}
